using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using DevExpress.Xpf.Grid;

namespace DNVLibrary.Planning
{
    /// <summary>
    /// UCGrid.xaml 的交互逻辑
    /// </summary>
    public partial class PShareGrid : UserControl
    {
        public PShareGrid()
        {
            InitializeComponent();
        }


        public List<string> reportFlags { get; set; }


        public void ButtonClick(string tag)
        {
            tmptag = tag;

            if (curtag != null && curtag == tmptag)
            {
                hidegrid(0);
                curtag = null;
            }
            else
                if (curtag != null)
                    hidegrid(0.2);
                else
                {
                    readdata(tmptag);
                    showgrid();
                    curtag = tmptag;
                }
            


        }



        private void grid_AutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            tableView1.BestFitColumns();

        }

        private void UserControl_Initialized(object sender, EventArgs e)
        {
            grid.Opacity = 0;
            //translate.Y=300;
            grid.IsHitTestVisible = false;
            ani.Completed += new EventHandler(ani_Completed);
        }

        void ani_Completed(object sender, EventArgs e)
        {
            if (curtag!=null && ani.To==0.2)
            //if (curtag != null && ani.To == 300)
            {
                readdata(tmptag);
                showgrid();
                curtag = tmptag;
            }
        }

        public string curtag = null;
        string tmptag = null;
        System.Windows.Media.Animation.DoubleAnimation ani = new System.Windows.Media.Animation.DoubleAnimation();

        void readdata(string tag)
        {
            System.Data.DataTable dt =  DataLayer.DataProvider.getDataTableFromSQL(string.Format("analqryc {0},'{1}'", 1, tag));
            grid.ItemsSource = dt.DefaultView;
        }
        void hidegrid(double to)
        {
            ani.Duration = TimeSpan.FromSeconds(0.3);
            ani.To = to;
            grid.BeginAnimation(OpacityProperty, ani);
            //ani.To = 300;
            //translate.BeginAnimation(TranslateTransform.YProperty, ani);
            grid.IsHitTestVisible = false;
        }

        void showgrid()
        {
            ani.Duration = TimeSpan.FromSeconds(0.8);
            ani.To = 1;
            grid.BeginAnimation(OpacityProperty, ani);
            //ani.To = 0;
            //translate.BeginAnimation(TranslateTransform.YProperty, ani);
            grid.IsHitTestVisible = true;
        }
    }
}
