//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNV863.WcfDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfDataService.IDataService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/test", ReplyAction="http://tempuri.org/IDataService/testResponse")]
        string test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDataTable", ReplyAction="http://tempuri.org/IDataService/GetDataTableResponse")]
        System.Data.DataTable GetDataTable(string sql, string datasourcename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ExecuteCommand", ReplyAction="http://tempuri.org/IDataService/ExecuteCommandResponse")]
        bool ExecuteCommand(string sql, string datasourcename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ReadSelfInfomation", ReplyAction="http://tempuri.org/IDataService/ReadSelfInfomationResponse")]
        DataLayer.WcfDataService.UserType ReadSelfInfomation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateSelfInfomation", ReplyAction="http://tempuri.org/IDataService/UpdateSelfInfomationResponse")]
        bool UpdateSelfInfomation(string Alias, string Password, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetManageData", ReplyAction="http://tempuri.org/IDataService/GetManageDataResponse")]
        System.Data.DataTable GetManageData(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetApplicationID", ReplyAction="http://tempuri.org/IDataService/GetApplicationIDResponse")]
        string GetApplicationID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateUserPassword", ReplyAction="http://tempuri.org/IDataService/UpdateUserPasswordResponse")]
        bool UpdateUserPassword(string userid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddNewUser", ReplyAction="http://tempuri.org/IDataService/AddNewUserResponse")]
        bool AddNewUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ExecuteManageCommand", ReplyAction="http://tempuri.org/IDataService/ExecuteManageCommandResponse")]
        bool ExecuteManageCommand(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CheckModelPermissionn", ReplyAction="http://tempuri.org/IDataService/CheckModelPermissionnResponse")]
        bool CheckModelPermissionn(string ModelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ReadLogInfomation", ReplyAction="http://tempuri.org/IDataService/ReadLogInfomationResponse")]
        DataLayer.WcfDataService.LogInfoType ReadLogInfomation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ReadLogs", ReplyAction="http://tempuri.org/IDataService/ReadLogsResponse")]
        System.Data.DataTable ReadLogs(System.DateTime start, System.DateTime end, string logtype);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : DNV863.WcfDataService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<DNV863.WcfDataService.IDataService>, DNV863.WcfDataService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string test() {
            return base.Channel.test();
        }
        
        public System.Data.DataTable GetDataTable(string sql, string datasourcename) {
            return base.Channel.GetDataTable(sql, datasourcename);
        }
        
        public bool ExecuteCommand(string sql, string datasourcename) {
            return base.Channel.ExecuteCommand(sql, datasourcename);
        }
        
        public DataLayer.WcfDataService.UserType ReadSelfInfomation() {
            return base.Channel.ReadSelfInfomation();
        }
        
        public bool UpdateSelfInfomation(string Alias, string Password, string Email) {
            return base.Channel.UpdateSelfInfomation(Alias, Password, Email);
        }
        
        public System.Data.DataTable GetManageData(string sql) {
            return base.Channel.GetManageData(sql);
        }
        
        public string GetApplicationID() {
            return base.Channel.GetApplicationID();
        }
        
        public bool UpdateUserPassword(string userid, string password) {
            return base.Channel.UpdateUserPassword(userid, password);
        }
        
        public bool AddNewUser(string username, string password) {
            return base.Channel.AddNewUser(username, password);
        }
        
        public bool ExecuteManageCommand(string sql) {
            return base.Channel.ExecuteManageCommand(sql);
        }
        
        public bool CheckModelPermissionn(string ModelName) {
            return base.Channel.CheckModelPermissionn(ModelName);
        }
        
        public DataLayer.WcfDataService.LogInfoType ReadLogInfomation() {
            return base.Channel.ReadLogInfomation();
        }
        
        public System.Data.DataTable ReadLogs(System.DateTime start, System.DateTime end, string logtype) {
            return base.Channel.ReadLogs(start, end, logtype);
        }
    }
}
